version: '3.9'

services: 

  # docker build --tag infinitydevops/express:1.0.5 ./
  # docker run --name express -p 8080:8080 
  app-express: 
    image: infinitydevops/express:1.1.0
    container_name: app-express
    build: ./app-express
    ports: 
      - 8080:8080
    volumes: 
      - "./app-express/src:/usr/www/app/src"
    networks: 
      - app-fullstack
    command: "npm run start"

  app-react: 
    image: "node:14.15.4"
    container_name: app-react
    working_dir: /usr/www/app
    ports: 
      - 3000:3000
    volumes: 
      - "./app-react:/usr/www/app/"
    networks: 
      - app-fullstack
    command: "npm run start"
    depends_on:
      - app-express
      


networks:
  app-fullstack: